Sensor data
waterloo-rocketry/state_estimation pull request #5
Opened 2020-10-09 19:05 UTC by usephysics

Added four new functions to rocket_math.py:

update_baro_pressure()
update_temperature()
update_body_acceleration()
update_magnetic_field()

Each function updates their respective property for a Rocket object.

Implemented these functions into data_generator.py's functions:
time_update()
write_data_to_file()

Added or modified unit tests for all new and modified functions, except for:

update_body_acceleration()
update_magnetic_field()

pending clarification and decisions for what magnetic field model will be used.

2020-10-10 03:02 UTC, dwkletke requested changes
> Reviewed 1 of 3 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5)* status: all files reviewed, 26 unresolved discussions (waiting on @jacobdeery and @usephysics)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJFAgk22EfKbSr1J5Qo:-MJFAgk22EfKbSr1J5Qp:behb6oj) (no related file):*
Overall, I think the sensor data generation looks great! There is a bit that needs to be fixed in `write_data_to_file()` but most of my comments are styling related.

One thing I should note is that I think you would benefit from using a linter or something like pylama to show where to clean up whitespace. This might also be a reason for me to adopt a format.sh script (like topside) into this project so that you just need to run that each time before the PRs.

Also, what is preventing you from writing unit tests for `update_body_acceleration()` and `update_magnetic_field()`? The magnetic field model should be independent of this since the model is for the world frame magnetic field, not the body frame (which 'update_magnetic_field()' currently updates). These functions can be tested with arbitrary numbers to verify their functionality as independent units. Feel free to ask me any questions if you need something clarified!

---
___
*[data_generator.py, line 22 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF5tQn06bA6MD8Ewrw:-MJF5tQn06bA6MD8Ewrx:bqv45z1) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L22)):*
> ```
> # has_negative = any([True if x < 0 else False for x in array])
> ```
I think this is a nice pythonic way of doing it.
___
*[data_generator.py, line 103 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF8J6G9W9kuqiUlVgp:-MJF8J6G9W9kuqiUlVgq:b-lnppum) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L103)):*
> ```
> ················································
> ```
Unneeded whitespace.
___
*[data_generator.py, line 112 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJFMtTu2AY4AgS0-4bH:-MJFMtTu2AY4AgS0-4bI:b-50qlfa) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L112)):*
> ```
> rocket.acceleration
> ```
Since you changed the variable name, this needs to be updated to `rocket.world_acceleration`.
___
*[data_generator.py, line 137 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJFNrXlExpjNgcil7w_:-MJFNrXlExpjNgcil7wa:b-o7mmor) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L137)):*
> ```
> body_acceleration
> ```
Should be world_acceleration.
___
*[data_generator.py, line 140 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJFNV4P2t4POdYfVqJX:-MJFNV4P2t4POdYfVqJY:blb9n5m) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L140)):*
> ```
>     sensor_data = np.array(
>         [str(rocket.baro_pressure), str(rocket.temperature),
>         np.array2string(rocket.body_acceleration), np.array2string(rocket.body_mag_field)])
> ```
I realized I didn't mention precision to you, so I think you should add that each variable has a 4 decimal precision to clean up the output to file. Something like this:
```
sensor_data = np.array(
        [f"{rocket.baro_pressure:.4f}", f"{rocket.temperature:.4f}",
         np.array2string(rocket.body_acceleration, precision=4,
                         floatmode='fixed'),
         np.array2string(rocket.body_mag_field, precision=4,
                         floatmode='fixed')])
```
___
*[data_generator.py, line 146 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF8SltAS5bpL2ZQ5Jm:-MJF8SltAS5bpL2ZQ5Jn:b-cxtas7) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L146)):*
> ```
> ········
> ```
More whitespace.
___
*[data_generator.py, line 147 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF4zQq0oNJQ9NVEaaT:-MJF4zQq0oNJQ9NVEaaU:b-x21doa) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L147)):*
> ```
> data_to_write = ' '.join(["{0: <33}".format(data) for data in gt_data])
> ```
I think you should change this variable name to `gt_data_to_write` to make it clear which data set this is.
___
*[data_generator.py, line 166 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJFOKf92HtP-eoPtu5q:-MJFOKf92HtP-eoPtu5r:by49hb5) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L166)):*
> ```
> "Angular_Rates\t"
> ```
Please remove this heading since it won't be needed.
___
*[data_generator.py, line 175 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJFNyG4-nFEJC4s9kR-:-MJFNyG4-nFEJC4s9kR0:by3t5kz) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L175)):*
> ```
> 16
> ```
Change this to 34 to match ground_truth.txt.
___
*[rocket_math.py, line 129 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF86zG45e2_CaZCr6v:-MJF86zG45e2_CaZCr6w:b-v4azg4) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L129)):*
> ```
> # [psi]
> ```
Please change this to KPa since it is currently implemented as KPa.
___
*[rocket_math.py, line 130 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF825G5gmK3xjL7-sQ:-MJF825G5gmK3xjL7-sR:buto1or) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L130)):*
> ```
> # in fahrenheit
> ```
Please change this to Celsius since it is currently implemented as Celsius.
___
*[rocket_math.py, line 209 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF62l15cli98tsOIhc:-MJF62l15cli98tsOIhd:bcgshxd) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L209)):*
> ```
> and all((self.body_mag_field - other.body_mag_field)·
> ```
Trailing whitespace.
___
*[rocket_math.py, line 212 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF5gbP8Hhi30RqIyz1:-MJF5gbP8Hhi30RqIyz2:b-yu971y) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L212)):*
> ```
> <= TOLERANCE)············
> ```
More trailing whitespace.
___
*[rocket_math.py, line 411 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF7rJhBos48HlK56QU:-MJF7rJhBos48HlK56QV:b-xft7yv) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L411)):*
> ```
> ····
> ```
More whitespace.
___
*[rocket_math.py, line 416 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF6yJG13b8nFxdIKbp:-MJF6yJG13b8nFxdIKbq:b-e9unot) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L416)):*
> ```
> https://web.archive.org/web/20200203025242/https://www.grc.nasa.gov/WWW/K-12/rocket/atmosmet.html
> ```
I am not entirely sure why I gave you this version of the link... I think you should change it to this one: https://www.grc.nasa.gov/WWW/K-12/airplane/atmosmet.html

P.S. Sorry that was my bad.
___
*[rocket_math.py, line 435 at r3](https://reviewable.io/reviews/wat [...]

2020-10-10 05:39 UTC, usephysics commented
I've added all theses changes, thanks @dwkletke!

I'll reach out to you soon to talk about the remaining 2 methods to implement.

2020-10-10 14:52 UTC, dwkletke requested changes
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5)* status: all files reviewed, 49 unresolved discussions (waiting on @jacobdeery and @usephysics)

___
*[data_generator.py, line 103 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF8J6G9W9kuqiUlVgp:-MJHsOEU9NKOmLatDKPo:b80wjlx) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L103)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> ················································
> ```
Unneeded whitespace.
</blockquote></details>

Sorry I meant after the code, not before. The spacing before `time_dict["timestep"])' is necessary, where as the spacing after is not.
___
*[data_generator.py, line 146 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF8SltAS5bpL2ZQ5Jm:-MJHsjQY0Wt9RC88uI1G:benpsw9) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L146)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> ········
> ```
More whitespace.
</blockquote></details>

Same comment as above.
___
*[data_generator.py, line 161 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHzaFG5T1DPJ-uOs8R:-MJHzaFH4bShoCm9H5TJ:b8e7731) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/data_generator.py#L161)):*
> ```
> Magnetic Field
> ```
I think this needs to be changed to `Magnetic_Field` to output properly to file.
___
*[rocket_math.py, line 416 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF6yJG13b8nFxdIKbp:-MJHtAsc2a_Cqgx2yaS1:b-vxta50) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L416)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> https://web.archive.org/web/20200203025242/https://www.grc.nasa.gov/WWW/K-12/rocket/atmosmet.html
> ```
I am not entirely sure why I gave you this version of the link... I think you should change it to this one: https://www.grc.nasa.gov/WWW/K-12/airplane/atmosmet.html

P.S. Sorry that was my bad.
</blockquote></details>

LMAO apparently I screwed up again and gave the airplane one (although they are no different except and airplane is in the background instead of a rocket lol)? Here is the rocket one: https://www.grc.nasa.gov/WWW/K-12/rocket/atmosmet.html

I think I got it right this time... XD
___
*[rocket_math.py, line 435 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF7Tb966o8Li_aRmyO:-MJHtWOU3F2lnVKT0jnn:b2nreh6) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L435)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> https://web.archive.org/web/20200203025242/https://www.grc.nasa.gov/WWW/K-12/rocket/atmosmet.html
> ```
Same here.
</blockquote></details>

Same as above.
___
*[rocket_math.py, line 447 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF7mRW6vvGjtml_zNN:-MJHtdSFEzvmelHD9NgD:b-ul0ds2) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/rocket_math.py#L447)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> ········
> ```
More whitespace.
</blockquote></details>

This still needs to be removed.
___
*[rocket_math.py, line 70 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHwDpQ2KcJfbq37ark:-MJHwDpQ2KcJfbq37arl:bo0y03b) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/rocket_math.py#L70)):*
> ```
> acceleration
> ```
Should be changed to `world_acceleration`. Additionally, the new variables you added should be added to this list.
___
*[tests/test_data_generator.py, line 163 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHueIKACO0zFVqnsIF:-MJHueIL70XAyG29H4K3:bpbixri) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L163)):*
> ```
> .acceleration
> ```
Forgot to mention this before, but this needs to be changed to `.world_acceleration`
___
*[tests/test_data_generator.py, line 215 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHur0E8SZaNZtuM5V3:-MJHur0E8SZaNZtuM5V4:b-hc2rhc) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L215)):*
> ```
> .acceleration
> ```
Same as above.
___
*[tests/test_data_generator.py, line 263 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHyKX24cxfhj3rltUA:-MJHyKX24cxfhj3rltUB:b-se1ere) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L263)):*
> ```
> "[0.0000 0.0000 1.0000]            \n")
> ```
I think there is 1 extra space between then end of the array and the newline character (since the test is failing for me).
___
*[tests/test_data_generator.py, line 302 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHyWlS2bJpSESWdJ-o:-MJHyWlS2bJpSESWdJ-p:brbwpip) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L302)):*
> ```
> "[0.0000 0.0000 1.0000]            \n")
> ```
Again, I think there might be an extra space since the test is failing for me.
___
*[tests/test_data_generator.py, line 309 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHuzXA4OKuTrfpafFy:-MJHuzXA4OKuTrfpafFz:b-hc2rhc) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L309)):*
> ```
> .acceleration
> ```
Same as above.
___
*[tests/test_data_generator.py, line 331 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHtuSe2ZZZs2HDIOFR:-MJHtuSe2ZZZs2HDIOFS:b-8kbqrh) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L331)):*
> ```
> ····
> ```
More whitespace here.
___
*[tests/test_data_generator.py, line 335 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHz0jACBJQJDHX9e6E:-MJHz0jACBJQJDHX9e6F:bey0td0) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L335)):*
> ```
> "[0.0000 0.0000 1.0000]            \n"
> ```
Again here.
___
*[tests/test_data_generator.py, line 339 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHyyQ30UPzlXOW50j5:-MJHyyQ30UPzlXOW50j6:bxcofdy) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L339)):*
> ```
> 0.0000 0.0000 2.0000]            \n")
> ```
And again here.
___
*[tests/test_data_generator.py, line 341 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHv1D6DcyItXPbZ8KR:-MJHv1D6DcyItXPbZ8KS:b-hc2rhc) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/605aee4a30d1f68f02fafd30f630e30ae333b145/tests/test_data_generator.py#L341)):*
> ```
> .acceleration
> ```
Same as above.
___
*[tests/test_data_generator.py, line 345 at r4](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJHtxsVC2Bk9h5YGtg6:-MJHtxsVC2Bk9h5YGtg7:b579qyn) ([raw file](https://github.com/ [...]

2020-10-10 18:48 UTC, dwkletke requested changes
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5)* status: all files reviewed, 52 unresolved discussions (waiting on @jacobdeery and @usephysics)

___
*[rocket_math.py, line 461 at r5](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJIp9tR-3zbAslApSaO:-MJIp9tR-3zbAslApSaP:bi8pkm7) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/42d2b24be875251ede1968e0b7ece05a53bce5f0/rocket_math.py#L461)):*
> ```
> ·
> ```
Trailing whitespace.
___
*[tests/test_data_generator.py, line 358 at r5](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJIpTL92hjuFLb_CbIL:-MJIpTL92hjuFLb_CbIM:b-mctawy) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/42d2b24be875251ede1968e0b7ece05a53bce5f0/tests/test_data_generator.py#L358)):*
> ```
> sd_file_value1 == sensor_valid1 and sd_file_value2 == sensor_valid2
> ```
This line should probably be indented to pass style standard.
___
*[tests/test_data_generator.py, line 360 at r5](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJInqnB7xNfIWkZU4dD:-MJInqnB7xNfIWkZU4dE:b-ngb13r) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/42d2b24be875251ede1968e0b7ece05a53bce5f0/tests/test_data_generator.py#L360)):*
> ```
> test_two_writes()
> ```
Not sure what this is doing here. If this was for testing (and in case you didn't know), to test the unit tests you just need to run `py.test` in your terminal (as long as you have all of the modules from `requirements.txt`).

P.S. I am going to add this and other general setup/usage things in a README for the repo.


<!-- Sent from Reviewable.io -->

2020-10-11 00:20 UTC, dwkletke reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5)* status: all files reviewed, 53 unresolved discussions (waiting on @jacobdeery and @usephysics)

___
*[data_generator.py, line 130 at r5](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJK0EIe6ZwFZLFLvNE8:-MJK0EIf7bMfOrRDX5Ig:bws9f90) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/42d2b24be875251ede1968e0b7ece05a53bce5f0/data_generator.py#L130)):*
> ```
>     new_gt_data = np.array(
>         [rocket.position, rocket.velocity,
>          rocket.world_acceleration, rocket.orientation])
> ```
This isn't from something you added, but when I updated to the newest numpy version there is a deprecation warning that get's generated due to the array being initialized with elements not of the same size. So to fix this (since we want to keep the array as is), please change this to:
```
new_data_gt = np.array(
        [rocket.position, rocket.velocity,
         rocket.acceleration, rocket.orientation], dtype=object)
```


<!-- Sent from Reviewable.io -->

2020-10-11 00:27 UTC, jacobdeery reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5)* status: all files reviewed, 54 unresolved discussions (waiting on @dwkletke and @usephysics)

___
*[data_generator.py, line 22 at r3](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJF5tQn06bA6MD8Ewrw:-MJFUPtu6IhyYhyRQdwH:bq2mmtw) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/5ed05ebc194b3959e640cb146391cbdea08eb3fe/data_generator.py#L22)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> # has_negative = any([True if x < 0 else False for x in array])
> ```
I think this is a nice pythonic way of doing it.
</blockquote></details>

an even cleaner way is `has_negative = any(array < 0)`
___
*[data_generator.py, line 130 at r5](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJK0EIe6ZwFZLFLvNE8:-MJK1xt_4Sb8OhBg7fC2:bx3yo8r) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/42d2b24be875251ede1968e0b7ece05a53bce5f0/data_generator.py#L130)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
>     new_gt_data = np.array(
>         [rocket.position, rocket.velocity,
>          rocket.world_acceleration, rocket.orientation])
> ```
This isn't from something you added, but when I updated to the newest numpy version there is a deprecation warning that get's generated due to the array being initialized with elements not of the same size. So to fix this (since we want to keep the array as is), please change this to:
```
new_data_gt = np.array(
        [rocket.position, rocket.velocity,
         rocket.acceleration, rocket.orientation], dtype=object)
```
</blockquote></details>

I would actually suggest just making this one (and `sensor_data`) a plain list rather than a numpy array, since we don't do anything numpy to it.
___
*[data_generator.py, line 140 at r5](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJK2DBh-v2pUJknaowl:-MJK2DBh-v2pUJknaowm:bfz0a62) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/42d2b24be875251ede1968e0b7ece05a53bce5f0/data_generator.py#L140)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     gt_data = ["", "", "", ""]
>     for i, data_elem_gt in enumerate(new_gt_data):
>         gt_data[i] = np.array2string(data_elem_gt, precision=4,
>                                             floatmode='fixed')
> ```
</details>

I think this can be simplified to:

`gt_data = [np.array2string(e, precision=4, floatmode='fixed') for e in new_gt_data]`


<!-- Sent from Reviewable.io -->

2020-10-11 00:30 UTC, dwkletke reviewed
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5)* status: all files reviewed, 54 unresolved discussions (waiting on @dwkletke, @jacobdeery, and @usephysics)

___
*[data_generator.py, line 130 at r5](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJK0EIe6ZwFZLFLvNE8:-MJK3Bba8HoG7sL2bzIZ:bhxtb0e) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/42d2b24be875251ede1968e0b7ece05a53bce5f0/data_generator.py#L130)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I would actually suggest just making this one (and `sensor_data`) a plain list rather than a numpy array, since we don't do anything numpy to it.
</blockquote></details>

Yeah that is a good point. That would fix this issue!


<!-- Sent from Reviewable.io -->

2020-10-11 04:24 UTC, usephysics commented
> an even cleaner way is `has_negative = any(array < 0)`

I should have tested it before committing, but I dont think this actually works

2020-10-11 15:20 UTC, dwkletke reviewed
> Reviewed 3 of 5 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5)* status: all files reviewed, 57 unresolved discussions (waiting on @dwkletke, @jacobdeery, and @usephysics)

___
*[data_generator.py, line 131 at r7](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJNC5C8-_AS7Y-GoHOm:-MJNC5C8-_AS7Y-GoHOn:b-cxtas7) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/772e2e1a069093b72923f8644f8a08200fd1d35e/data_generator.py#L131)):*
> ```
> ········
> ```
More whitespace.
___
*[data_generator.py, line 133 at r7](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJNCtKPAXELZ-zbofQL:-MJNCtKPAXELZ-zbofQM:b579qyn) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/772e2e1a069093b72923f8644f8a08200fd1d35e/data_generator.py#L133)):*
> ```
> ·
> ```
Whitespace.
___
*[rocket_math.py, line 461 at r7](https://reviewable.io/reviews/waterloo-rocketry/state_estimation/5#-MJNDEhC80pYeRi5Vmi9:-MJNDEhC80pYeRi5VmiA:b4tu69t) ([raw file](https://github.com/waterloo-rocketry/state_estimation/blob/772e2e1a069093b72923f8644f8a08200fd1d35e/rocket_math.py#L461)):*
> ```
> Numpy array representing the body (proper) acceleration
> ```
Maybe add units to description like:
`Numpy array representing the body (proper) acceleration in m/s^2.`


<!-- Sent from Reviewable.io -->

2020-10-11 21:52 UTC, jacobdeery commented
> I should have tested it before committing, but I dont think this actually works

What error are you running into?

2020-10-11 21:56 UTC, usephysics commented
> > I should have tested it before committing, but I dont think this actually works
> 
> What error are you running into?

Oh, I tested it using a normal Python list, didn't realize it worked on numpy arrays. My bad, will revert

2020-10-13 23:41 UTC, merged